---
name: "🚀 Sprint Planning"
about: Conduct a Sprint Planning meeting.
labels: 
  - "type: sprint-planning :runner:"
  - "type: team-update"
  - "type: internal-pm"
title: "Sprint Planning Meeting: <add date>"
---

#  Accessibility - Sprint Planning meeting

This is a **60 minute** recurring meeting **every 6 weeks** 

Our goal is to synchronize the team on the most important things to work on, and to divide work between one another so we know what to work on next.

- [**Team backlog**](https://github.com/orgs/Quansight-Labs/projects/5)
  - [List items on a milestone view](https://github.com/orgs/Quansight-Labs/projects/5/views/5?query=is%3Aopen+sort%3Aupdated-desc)

- **Meeting facilitator**: <github-handle>

### Meeting agenda

**Review Grant Deliverables.** (15 min)

The PI will do the following:

- Share accomplishments since the last sprint, demos, etc
- Discuss any major questions to answer
- Discuss the work plan for the next sprint for this project

Additionally:

- Discuss any open RFD (requests for discussion in-flight)


**Assign backlog items** (40 min)

The whole team:

1. Go over the existing backlog for the new milestone (need to look at grant's milestones)
2. Assign issues as needed - make sure they reflect the sprint's milestone
3. Add any intermediate tasks needed to complete the issues and make assignments

**Wrap up** (10 mins)

- Update the issue and notes 
- Raise up any other concerns/questions/etc.