name: Open a weekly team update issue
on:
  # schedule:
    # Run every Tuesday at 13:00 (5:00 on PDT )
    # - cron: "00 13 * * WED"

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  open-sync-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install ghapi

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Post team sync issue
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "name=ISSUE_URL::$(python scripts/post-team-update.py)" >> $GITHUB_OUTPUT
        id: newsync

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: jupyter-a11y-czi
          SLACK_COLOR: "#7868E6"
          SLACK_MESSAGE: "Time to fill the weekly update :pencil: <${{ steps.newsync.outputs.ISSUE_URL }}>"
          SLACK_USERNAME: "GH-bot"
          SLACK_ICON_EMOJI: ":github-1:"
          MSG_MINIMAL: true
